server:
  port: 8080

spring:
  application:
    name: godo
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2s
      connect-timeout: 2s
  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
